gardener/gardener-extension-os-gardenlinux

pkg/generator/templates/cloud-init.gardenlinux.template
pkg/generator/testfiles/cloud-init

Preload `nfsd` module
Mitigate https://github.com/docker/for-linux/issues/996
```improvement user
`nfsd` module is now preloaded for both existing and newly created VMs with Garden Linux.
```

preload nfsd module

---

pkg/generator/templates/cloud-init.gardenlinux.template
pkg/generator/testfiles/cloud-init
pkg/generator/testfiles/containerd-bootstrap
pkg/generator/testfiles/containerd-reconcile
pkg/generator/testfiles/docker-bootstrap
pkg/generator/testfiles/docker-reconcile

Temporary mitigation of https://github.com/gardenlinux/gardenlinux/issues/107 till it is permanently fixed in the Garden Linux.
Mitigates https://github.com/gardenlinux/gardenlinux/issues/107
```improvement user
Mitigate an issue observed on Azure shoot clusters where Garden Linux VMs do not register their hostnames with the DHCP server. 
```

mitigate failing to resolve cluster's VM hostname

---

pkg/generator/templates/cloud-init.gardenlinux.template
pkg/generator/testfiles/cloud-init
pkg/generator/testfiles/containerd-bootstrap
pkg/generator/testfiles/docker-bootstrap

/area os
A mitigation for Garden linux 27.1 and 27.0 that do:
- install cifs-utils from the package registry (done in the upstream https://github.com/gardenlinux/gardenlinux/pull/103)
- increase the memlock limit for docker containers to mitigate https://github.com/golang/go/wiki/LinuxKernelSignalVectorBug (done in the upstream https://github.com/gardenlinux/gardenlinux/pull/128)
Fixes #
/cc @ccwienk @hoeltcl @gehoern 
```improvement user
Docker memory lock limit is increased to 64MB (needed to mitigate https://github.com/golang/go/wiki/LinuxKernelSignalVectorBug) and cifs-utils …
```

[gl-27] Increase docker memorylock limit and install cifs-utils

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/pull_request_template.md
hack/update-github-templates.sh
pkg/generator/templates/cloud-init.gardenlinux.template
pkg/generator/testfiles/cloud-init
pkg/generator/testfiles/containerd-bootstrap
pkg/generator/testfiles/containerd-reconcile
pkg/generator/testfiles/docker-bootstrap
pkg/generator/testfiles/docker-reconcile

/area os
cifs-utils package will be installed even on existing Garden Linux 27.[0|1] nodes.
Follow up on #14
```improvement user
[Previously](https://github.com/gardener/gardener-extension-os-gardenlinux/pull/14/), `cifs-utils` was installed only on newly created Garden Linux nodes, now it is installed also on already existing nodes that are missing this package.
```

[gl-27] Install cifs-utils on existing nodes

---

pkg/generator/templates/cloud-init.gardenlinux.template
pkg/generator/testfiles/cloud-init
pkg/generator/testfiles/containerd-bootstrap
pkg/generator/testfiles/containerd-reconcile
pkg/generator/testfiles/docker-bootstrap
pkg/generator/testfiles/docker-reconcile

/area os
/assign @mvladev 
/invite @mvladev 
Install xfsprogs package on GL 27.0 and 27.1 nodes.
Fixes #
The upstream change is here https://github.com/gardenlinux/gardenlinux/commit/17f223a7826b41a727656798df59b57f4e7300b1
```improvement user
`xfsprogs` package is installed (required to enable xfs volumes) on Garden Linux 27.0 and 27.1 nodes.
```

[gl-27] Install xfsprogs

---

.github/ISSUE_TEMPLATE/flaking-test.md
.github/pull_request_template.md
Dockerfile

/kind task
Update golang to 1.15.5 and alpine to 3.12.1.
Fixes #
```improvement operator
The golang has been upgraded to 1.15.5.
```
```improvement operator
The alpine base image has been upgraded to 3.12.1.
```

Update golang and alpine

---

pkg/generator/templates/cloud-init.gardenlinux.template
pkg/generator/testfiles/cloud-init
pkg/generator/testfiles/containerd-bootstrap
pkg/generator/testfiles/containerd-reconcile
pkg/generator/testfiles/docker-bootstrap
pkg/generator/testfiles/docker-reconcile

/area os
/kind cleanup
Remove support for Garden Linux 27.0 and 27.1
Fixes #
```breaking operator
:warning: Support for Garden Linux versions 27.0 and 27.1 has been removed from this extension. Please, ensure that all shoot clusters in your landscape are running on Garden Linux 184.0 or newer version before upgrading to this version of the extension.
```

Remove support for Garden Linux 27.0 and 27.1

---

README.md
example/30-secret.yaml
example/40-operatingsystemconfig.yaml

/area dev-productivity
The default token secret has different name in each k8s cluster.
Therefore it is always required to update the examples in order to use them.
Fixes #
```other operator
```

Use dedicated secret for the sample OSC

---

.ci/component_descriptor
.landscaper/blueprint/blueprint.yaml
.landscaper/blueprint/deploy-executions.yaml
.landscaper/component-descriptor.yaml
.landscaper/resources.yaml

/area TODO
adds artifacts for Landscaper integration (blueprint, resources definition file, component descriptor build script)
co-authored by @enrico-kaack-comp 
Fixes #
```feature operator
- adds artifacts for Landscaper integration
```

landscaper integration

---

README.md

Not sure if this was ever working before.

Fix `oscommon` link to g/g repo

---

CODEOWNERS

Fix gardenlinux team name in CODEOWNERS

Fix gardenlinux team name in CODEOWNERS

---

pkg/generator/templates/cloud-init.gardenlinux.template
pkg/generator/testfiles/containerd-bootstrap

/area os
Initialize containerd config.toml file as early as possible.
This is needed because with the `/etc/systemd/system/containerd.service.d/11-exec_config.conf` drop-in containerd is re-configured to use this file, but it does not exist and containerd will not be able to start-up as long as the file is missing. 
As docker is using containerd, and Gardener installs kubectl and kubelet via image pulled by docker, this extension must make everything to ensure that containerd always uses an existing configuration file.
Fixes #
Similar to https://github.com/gardener/gardener-extension-os-ubuntu/pull/52. 
**Release …

Initialize containerd config.toml file as early as possible

---

Makefile

/area os
/kind bug
Fix `make revendor` command order to be like [gardener's make revendor](https://github.com/gardener/gardener/blob/master/Makefile#L196)
```other developer
NONE
```

Fix make revendor command order

---

.github/dependabot.yaml
.github/workflows/vendor_gardener.yaml

Configures dependabot and github actions to create automatic gardener/gardener dependency updates.
Linked to https://github.com/gardener/gardener/issues/6328
Part of https://github.com/gardener/gardener/issues/6328
N/A
```other developer
The os-gardenlinux extension does now enable dependabot for automatic dependency update PRs for the `github.com/gardener/gardener` dependency.
```

Enable dependabot

---

.github/workflows/vendor_gardener.yaml

/kind bug
The currently used user does not sign the CLA. This adapt changes the user to `gardener-robot-ci-1`.
```other operator
NONE
```

Adapt the "Vendor Gardener" github action to use the gardener-robot-ci-1 user

---

README.md

This PR fixes broken links in the documentation. As the `oscommon` package was removed in [the following PR](https://github.com/gardener/gardener/commit/84f525624b9aff02e8b3dcd6102f1584f89d87b2), I will be removing the line that references it in the README.md
/area os
/area documentation
Fixes #
```doc developer
NONE
```

Fixed broken links - 2024.05

---

pkg/controller/operatingsystemconfig/actuator.go
pkg/controller/operatingsystemconfig/actuator_test.go

/area os
/kind bug
Gardener Node Agent deletes all service unit drop ins if none is known to him. Adding the drop-in file ensures the directory is not deleted. The `override.conf` is currently part of garden linux but might be removed in the future.
Fixes #
```other operator
Adds an override.conf containerd dropin file to set LimitMEMLOCK and LimitNOFILE
```

add override.conf containerd dropin to set LimitMEMLOCK and LimitNOFILE

---

Makefile

/area os
/kind technical-debt
Changes the Makefile to use docker buildx to build container images for this extensions so that we can build images for multiple architectures with `linux/amd64` being the default.
```other operator
Container images for the gardenlinux extension are now built with Docker buildx to enable cross-platform builds and default to the `linux/amd64` architecture.
```

Use buildx to build docker images

---

pkg/controller/operatingsystemconfig/actuator.go
pkg/controller/operatingsystemconfig/actuator_test.go

/area os
/kind cleanup
cleanup /etc/systemd/system/containerd.service.d/11-exec_config.conf & /etc/containerd/config.toml as they only contain default settings
Fixes #
```other operator
remove 11-exec_config.conf & config.toml file creation
```

remove 11-exec_config.conf & config.toml file creation

---

pkg/controller/operatingsystemconfig/actuator.go
pkg/controller/operatingsystemconfig/actuator_test.go

/area os
/kind bug
This reverts commit 5cc43cf13af4a4092b8fb5ed7768c758ffdcfd9b. During investigation, it was found out that creating the file `11-exec_config.conf` - even though it just tells containerd to read its configuration from the default location - is required to influence containerds behaviour in case the file is missing.
Fixes #
```bugfix operator
Previous removal of `11-exec_config.conf` systemd drop-in for containerd from the provision OSC was reverted, the file gets created again.
```

Revert "remove 11-exec_config.conf file creation"

---

pkg/controller/operatingsystemconfig/actuator.go
pkg/controller/operatingsystemconfig/actuator_test.go

/area os
/kind cleanup
This PR removes executions of docker commands in the init OperatingSystemConfig.
From Gardener side, the `docker` binary is no longer used/required on a Shoot Node: https://github.com/gardener/gardener/issues/4673.
From gardeninux OS side, [gardenlinux@1443.1+](https://github.com/gardenlinux/gardenlinux/releases/tag/1443.1) no longer includes the `docker` binary unit in the OS.
N/A
N/A
```other operator
The os-gardenlinux extension does no longer enable and restart the `docker` unit as part of the init OperatingSystemConfig. Gardener and Kubernetes does no longer support `docker` as CRI. …
```

Remove docker from the `provision` OperatingSystemConfig

---

README.md
example/40-operatingsystemconfig-gardenlinux.yaml
example/40-operatingsystemconfig-memoryonegardenlinux.yaml

/area os
/kind cleanup
The Garden Linux extension no longer supports anything related to Docker since PR #221 so we should also remove all references to Docker units from the example and README files.
```other operator
NONE
```

Chore: remove docker references from documentation

---

.ci/pipeline_definitions

/area os
Adds Vincinator as responsible for this repository in component-descriptor.
```other operator
NONE
```

add vincinator as responsible

---

pkg/controller/operatingsystemconfig/actuator.go
pkg/gardenlinux/constants.go
pkg/gardenlinux/scripts/inplace-update.sh

/area os
This PR adds support for in-place OS updates for gardenlinux.
A script is added which calls the `gardenlinux-update` tool and interprets the returned error (see [here](https://github.com/gardenlinux/package-gardenlinux-update/blob/6994939d060fb587ceb0f958b95a3ac56315c61f/src/main.go#L405-L407)) in a manner which `gardener-node-agent` understands. [Ref](https://github.com/gardener/gardener/blob/e1f4d645071a5422259066ae34097327d3c1ba36/pkg/nodeagent/controller/operatingsystemconfig/reconciler.go#L71-L72)
The used machine image still needs to support in-place updates in the cloudprofile, See [example](https://github.com/gardener/gardener/blob/e1f4d645071a5422259066ae34097327d3c1b …

[GEP-31] Add support for in-place OS updates

---

README.md

/area os
/kind cleanup
Updates the CI status badge to point to GitHub actions after GHA workflow name change.
```other operator
NONE
```

Update CI build status badge (again)
